[tool.poetry]
name = "library-registry-submission-parser"
version = "0.0.0"
description = "Arduino Library Manager submission parser"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

# Integration tests dependencies.
invoke = "1.6.0"
pytest = "6.2.4"

black = { version = "^21.7b0", allow-prereleases = true }
codespell = ">=2.0.0"
flake8 = "^3.9.2"
pep8-naming = "^0.12.1"

[tool.black]
line-length = 120
target-version = ["py39"]
