[tool.poetry]
name = "library-registry-submission-parser"
version = "0.0.0"
description = "Arduino Library Manager submission parser"
authors = ["Arduino <info@arduino.cc>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^22.8"
flake8 = "^5.0.4"
pep8-naming = "^0.13.2"
codespell = "^2.2.1"
pytest = "7.1.3"
invoke = "1.7.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py39"]
