# See: https://taskfile.dev/#/usage
version: "3"

vars:
  DEFAULT_GO_PACKAGES:
    sh: echo $(go list ./... | tr '\n' ' ')

tasks:
  check:
    desc: Check for problems with the project
    deps:
      - task: go:test

  go:build:
    desc: Build the project
    cmds:
      - go build -v {{.GO_BUILD_FLAGS}}

  go:test:
    desc: Run unit tests
    cmds:
      - go test -v -short -run '{{default ".*" .GO_TEST_REGEX}}' {{default "-timeout 10m -coverpkg=./... -covermode=atomic" .GO_TEST_FLAGS}} -coverprofile=coverage_unit.txt {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}

