# See: https://taskfile.dev/#/usage
version: "3"

vars:
  DEFAULT_GO_PACKAGES:
    sh: echo $(go list ./... | tr '\n' ' ')

  PRETTIER: prettier@2.2.1

tasks:
  check:
    desc: Check for problems with the project
    deps:
      - task: go:test
      - task: general:check-spelling

  go:build:
    desc: Build the project
    cmds:
      - go build -v {{.GO_BUILD_FLAGS}}

  go:test:
    desc: Run unit tests
    cmds:
      - go test -v -short -run '{{default ".*" .GO_TEST_REGEX}}' {{default "-timeout 10m -coverpkg=./... -covermode=atomic" .GO_TEST_FLAGS}} -coverprofile=coverage_unit.txt {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}

  general:format:
    desc: Format all supported files with Prettier
    cmds:
      - npx {{.PRETTIER}} --write .

  general:check-spelling:
    desc: Check for commonly misspelled words
    cmds:
      - poetry install --no-root
      - poetry run codespell {{.CODESPELL_SKIP_OPTION}} {{.CODESPELL_IGNORE_WORDS_OPTION}}

  general:correct-spelling:
    desc: Correct commonly misspelled words where possible
    cmds:
      - poetry install --no-root
      - poetry run codespell --write-changes {{.CODESPELL_SKIP_OPTION}} {{.CODESPELL_IGNORE_WORDS_OPTION}}
