# Source:
# https://github.com/arduino/tooling-project-assets/blob/main/issue-templates/template-choosers/general/config.yml
# See:
# https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

blank_issues_enabled: false
contact_links:
  - name: Learn about the Arduino Library Manager registry
    url: https://github.com/arduino/library-registry#readme
    about: arduino/library-registry-submission-parser is a component of the Arduino Library Manager registry infrastructure.
  - name: Support request
    url: https://forum.arduino.cc/
    about: We can help you out on the Arduino Forum!
  - name: Discuss development work on the project
    url: https://groups.google.com/a/arduino.cc/g/developers
    about: Arduino Developers Mailing List
